# Server configuration
server.port=8081

# Application name
spring.application.name=USER-SERVICE

# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=user_db
# If you have authentication enabled:
# spring.data.mongodb.username=your_username
# spring.data.mongodb.password=your_password
# spring.data.mongodb.authentication-database=admin

# Eureka Configuration
eureka.client.service-url.defaultZone=http://eureka:8761/eureka
eureka.instance.prefer-ip-address=true
