# Server
server.port=8082

# Application
spring.application.name=media-service

# MongoDB
spring.data.mongodb.uri=mongodb://${MONGO_ROOT_USERNAME:admin}:${MONGO_ROOT_PASSWORD:admin123}@${MONGODB_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DATABASE:media_db}?authSource=admin
spring.data.mongodb.auto-index-creation=true

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# JWT (same secret as User-Service so this service can validate tokens)
jwt.secret=${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}

# MinIO
minio.endpoint=${MINIO_ENDPOINT:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
minio.bucket=${MINIO_BUCKET:media-files}
# Public URL the browser uses to load images (can differ from internal endpoint)
minio.public-endpoint=${MINIO_PUBLIC_ENDPOINT:http://localhost:9000}

# Multipart – allow up to 10 MB per upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
