# Test profile – uses Flapdoodle embedded MongoDB
spring.data.mongodb.auto-index-creation=true
spring.autoconfigure.exclude=

# Disable Eureka registration during tests
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# JWT (test secret)
jwt.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
jwt.expiration=86400000
jwt.refresh-expiration=604800000
